name: Update IBC Support

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
    resources:
        name: Update IBC Support Data
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 16.13.0
            - name: Get Deps
              run: npm install
            - name: Fetch Data
              run: npm run fetch
            - name: Update DB
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: "data/**/*.json"
                  commit-msg: update ibc support data
                  github-token: ${{ secrets.GITHUB_TOKEN }}
